#DEFINE 5 NUMBERS
    #IF NUM1 IS GREATER THAN NUM2
        #COMPARE NUM1 TO OTHER NUMBERS
        #IF NUM2 IS GREATER THAN NUM1
    
    #IF NUM2 IS GREATER THAN NUM3
        #COMPARE NUM2 TO OTHER NUMBERS
        #IF NUM3 IS GREATER THAN NUM2
    
    #IF NUM3 IS GREATER THAN NUM4
        #COMPARE NUM3 TO OTHER NUMBERS
        #IF NUM4 IS GREATER THAN NUM3
    
    #IF NUM4 IS GREATER THAN NUM5
        #IF NUM5 IS GREATER THAN NUM4

#INPUT FIVE NUMBERS

#PRINT THE HIGHEST NUMBER